-- SmartCode: Organization Assignment + Auto-Visibility requirement -
-- Coder<->Team membership history (backing the Team Lead's "Relieve from
-- Team" / "Release from Team" action) and an Auditor<->Project
-- soft-delete fix (so unassigning an Auditor from a Project no longer
-- destroys history). Forward-only and additive: one new enum, one new
-- table with foreign keys only to existing tables ("Team", "User"), and
-- three new nullable/defaulted columns on the existing
-- "AuditorProjectAssignment" table. No existing column, row, constraint
-- or index on any OTHER table is changed, altered or removed, and
-- User.teamId / Project.teamId are left completely untouched - every
-- existing scope query that reads them keeps working exactly as before.

-- CreateEnum
CREATE TYPE "TeamMembershipEndReason" AS ENUM ('RELIEVED', 'REASSIGNED');

-- CreateTable
CREATE TABLE "TeamMembership" (
    "id" TEXT NOT NULL,
    "coderId" TEXT NOT NULL,
    "teamId" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assignedById" TEXT,
    "endedAt" TIMESTAMP(3),
    "endedById" TEXT,
    "endReason" "TeamMembershipEndReason",

    CONSTRAINT "TeamMembership_pkey" PRIMARY KEY ("id")
);

-- CreateIndex (ordinary, non-unique - history/list queries)
CREATE INDEX "TeamMembership_coderId_isActive_idx" ON "TeamMembership"("coderId", "isActive");

-- CreateIndex
CREATE INDEX "TeamMembership_teamId_isActive_idx" ON "TeamMembership"("teamId", "isActive");

-- CreatePartialUniqueIndex: at most one ACTIVE (isActive = true) team
-- membership per Coder at any time - matching User.teamId's own "one team
-- at a time" semantics. Prisma's schema DSL cannot express a partial
-- (WHERE-filtered) unique index, so - exactly like ProjectTeamAssignment/
-- VendorAssignment/ChartAllocation's equivalent invariants above - this is
-- enforced here, directly in SQL, and documented on the TeamMembership
-- model in schema.prisma.
CREATE UNIQUE INDEX "TeamMembership_coderId_active_key"
    ON "TeamMembership"("coderId")
    WHERE "isActive" = true;

-- AddForeignKey
ALTER TABLE "TeamMembership" ADD CONSTRAINT "TeamMembership_coderId_fkey" FOREIGN KEY ("coderId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TeamMembership" ADD CONSTRAINT "TeamMembership_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey ("assignedById"/"endedById" nullable - actor columns,
-- SET NULL not RESTRICT, mirroring this schema's other "who did this"
-- actor columns so a later user deletion, if ever implemented, can never
-- be blocked by old history.)
ALTER TABLE "TeamMembership" ADD CONSTRAINT "TeamMembership_assignedById_fkey" FOREIGN KEY ("assignedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TeamMembership" ADD CONSTRAINT "TeamMembership_endedById_fkey" FOREIGN KEY ("endedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- NOTE: existing Coder<->Team relationships (every User.teamId already
-- set before this migration) are intentionally NOT backfilled into
-- TeamMembership here, for the exact same reason LoginNameAllocation's
-- initial backfill was done through the Prisma client rather than raw
-- SQL (see that migration's own NOTE): every "id" in this schema is
-- generated by the Prisma client at insert time, not by a DB-side
-- default, so a raw-SQL INSERT would have to depend on
-- gen_random_uuid() - a function this migration has no way to verify is
-- available on your database. This does not lose any information that
-- exists today: User.teamId (the current-state pointer every scope
-- helper reads) is completely unchanged, and the very next time any
-- existing Coder's team membership changes (a fresh assignment, a
-- "Relieve from Team", a reassignment), the ledger begins recording it
-- going forward through CodersService, exactly as ProjectTeamAssignment
-- began recording Project<->Team history going forward without
-- backfilling pre-existing Project.teamId values.

-- AlterTable: three new columns on the existing AuditorProjectAssignment
-- table - "isActive" NOT NULL DEFAULT true means every existing row (an
-- Auditor's assignment that has never been unassigned, since unassigning
-- used to hard-delete the row entirely - see ProjectsService#deleteAssignment
-- before this migration) is correctly backfilled to true. "removedAt"/
-- "removedById" are nullable and correctly NULL for every existing row,
-- since no currently-existing row has ever been "removed" under the new
-- soft-delete behaviour this migration enables going forward.
ALTER TABLE "AuditorProjectAssignment" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AuditorProjectAssignment" ADD COLUMN "removedAt" TIMESTAMP(3);
ALTER TABLE "AuditorProjectAssignment" ADD COLUMN "removedById" TEXT;

-- DropIndex: the old `@@unique([auditorId, projectId])` only ever worked
-- because unassigning was a hard delete that freed the pair for reuse.
-- Now that unassigning is a soft-delete, this whole-table unique
-- constraint would incorrectly block re-assigning the same Auditor to the
-- same Project after a later unassignment - dropped in favour of the
-- partial unique index below, which expresses the invariant this
-- constraint actually existed for ("no two simultaneously ACTIVE
-- assignments for the same Auditor+Project pair").
DROP INDEX "AuditorProjectAssignment_auditorId_projectId_key";

-- CreateIndex (ordinary, non-unique - history/list queries)
CREATE INDEX "AuditorProjectAssignment_auditorId_isActive_idx" ON "AuditorProjectAssignment"("auditorId", "isActive");

-- CreateIndex
CREATE INDEX "AuditorProjectAssignment_projectId_isActive_idx" ON "AuditorProjectAssignment"("projectId", "isActive");

-- CreatePartialUniqueIndex: at most one ACTIVE assignment per
-- (auditorId, projectId) pair - the replacement for the dropped
-- whole-table unique constraint, scoped to isActive = true so a
-- previously-ended assignment for the same pair never blocks a fresh one.
CREATE UNIQUE INDEX "AuditorProjectAssignment_auditorId_projectId_active_key"
    ON "AuditorProjectAssignment"("auditorId", "projectId")
    WHERE "isActive" = true;

-- AddForeignKey
ALTER TABLE "AuditorProjectAssignment" ADD CONSTRAINT "AuditorProjectAssignment_removedById_fkey" FOREIGN KEY ("removedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
