-- SmartCode: Login Name Allocation history (docs/09-BUSINESS-RULES.md
-- section 10 / Phase 9) - an append-only ledger of who has held every
-- Login Name, and when. Forward-only and additive: one new enum, one new
-- table, foreign keys only to the existing "User" table, plus a one-time
-- idempotent backfill for existing users. No existing column, row,
-- constraint or index is changed, altered or removed.

-- CreateEnum
CREATE TYPE "LoginNameAllocationStatus" AS ENUM ('ACTIVE', 'DEACTIVATED', 'REALLOCATED');

-- CreateTable
CREATE TABLE "LoginNameAllocation" (
    "id" TEXT NOT NULL,
    "loginName" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "status" "LoginNameAllocationStatus" NOT NULL DEFAULT 'ACTIVE',
    "allocatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deallocatedAt" TIMESTAMP(3),
    "allocatedById" TEXT,
    "deallocatedById" TEXT,
    "reason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LoginNameAllocation_pkey" PRIMARY KEY ("id")
);

-- CreateIndex (ordinary, non-unique - for search/filter/history queries)
CREATE INDEX "LoginNameAllocation_loginName_idx" ON "LoginNameAllocation"("loginName");

-- CreateIndex
CREATE INDEX "LoginNameAllocation_userId_idx" ON "LoginNameAllocation"("userId");

-- CreateIndex
CREATE INDEX "LoginNameAllocation_status_idx" ON "LoginNameAllocation"("status");

-- CreatePartialUniqueIndex: at most one ACTIVE allocation per Login Name.
-- Prisma's schema DSL cannot express a partial (WHERE-filtered) unique
-- index, so this invariant is enforced here, directly in SQL, and
-- documented on the LoginNameAllocation model in schema.prisma. Two
-- REALLOCATED/DEACTIVATED rows may freely share the same loginName
-- (that is the whole point of the history), but never two ACTIVE ones.
CREATE UNIQUE INDEX "LoginNameAllocation_loginName_active_key"
    ON "LoginNameAllocation"("loginName")
    WHERE "status" = 'ACTIVE';

-- CreatePartialUniqueIndex: at most one ACTIVE allocation per User.
CREATE UNIQUE INDEX "LoginNameAllocation_userId_active_key"
    ON "LoginNameAllocation"("userId")
    WHERE "status" = 'ACTIVE';

-- AddForeignKey
ALTER TABLE "LoginNameAllocation" ADD CONSTRAINT "LoginNameAllocation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey ("allocatedById" is nullable - see schema.prisma comment:
-- null marks a system-origin INITIAL_BACKFILL row for a pre-Phase-9
-- account, never a fabricated actor, so ON DELETE SET NULL matches
-- "deallocatedById" below rather than RESTRICT.)
ALTER TABLE "LoginNameAllocation" ADD CONSTRAINT "LoginNameAllocation_allocatedById_fkey" FOREIGN KEY ("allocatedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LoginNameAllocation" ADD CONSTRAINT "LoginNameAllocation_deallocatedById_fkey" FOREIGN KEY ("deallocatedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- NOTE on "allocatedById": nullable because the one-time backfill below
-- has no real human actor to record for a pre-existing account - it is
-- never attributed to the account holder themselves, and no fake Manager
-- is invented. This mirrors "AuditLog"."userId", already nullable in this
-- schema for exactly this kind of system-origin row.
--
-- NOTE: existing users are intentionally NOT backfilled here. Every "id"
-- column in this schema is generated by the Prisma client at insert time
-- (see every other model's plain "id" TEXT NOT NULL with no DB-level
-- DEFAULT) rather than by a Postgres-side function, so a raw-SQL INSERT
-- in this migration would have to depend on gen_random_uuid() - a
-- function this schema has never relied on and whose availability
-- (core in Postgres 13+, extension-gated before that) this migration has
-- no way to verify against your database. Backfilling through Prisma's
-- own client instead keeps ID generation consistent with every other row
-- in this database and is fully idempotent/re-runnable.
--
-- Run once after this migration (see apps/api/scripts/backfill-login-name-allocations.ts):
--   pnpm --filter @smartcode/api exec ts-node scripts/backfill-login-name-allocations.ts
